#!/usr/bin/env node

/**
 * Kimi Search CLI - 使用Kimi AI进行联网搜索并构建本地知识库
 * 
 * 功能：
 * 1. 使用kimi_cli进行联网搜索
 * 2. 整理搜索结果并保存到本地
 * 3. 生成知识库索引和快捷说明书
 * 4. 适用于创建Agents、查找人设信息、构建知识库等场景
 */

import { spawn } from 'child_process';
import { promises as fs } from 'fs';
import { homedir } from 'os';
import path from 'path';

// 配置
const CONFIG = {
  // 知识库默认保存位置
  knowledgeBaseDir: process.env.KIMI_SEARCH_DIR || path.join(homedir(), 'Desktop', 'kimi-knowledge-base'),
  // 默认搜索深度
  defaultDepth: 'standard', // 'quick', 'standard', 'deep'
  // 最大重试次数
  maxRetries: 2,
  // kimi cli 路径
  kimiPath: 'kimi'
};

/**
 * 执行kimi命令进行搜索
 * @param {string} query - 搜索查询
 * @param {Object} options - 搜索选项
 * @returns {Promise<string>} - 搜索结果
 */
async function kimiSearch(query, options = {}) {
  const { depth = CONFIG.defaultDepth, context = '' } = options;
  
  // 构建搜索提示词
  let searchPrompt = buildSearchPrompt(query, depth, context);
  
  console.log(`🔍 正在使用Kimi进行搜索: "${query}"`);
  console.log(`📊 搜索深度: ${depth}`);
  
  return new Promise((resolve, reject) => {
    let output = '';
    let errorOutput = '';
    
    // 使用kimi -p参数直接传递搜索提示
    const kimiArgs = [
      '-p', searchPrompt,
      '-y' // 自动确认
    ];
    
    const kimi = spawn(CONFIG.kimiPath, kimiArgs, {
      cwd: process.cwd(),
      env: process.env
    });
    
    kimi.stdout.on('data', (data) => {
      const chunk = data.toString();
      output += chunk;
      process.stdout.write(chunk);
    });
    
    kimi.stderr.on('data', (data) => {
      const chunk = data.toString();
      errorOutput += chunk;
      process.stderr.write(chunk);
    });
    
    kimi.on('close', (code) => {
      if (code !== 0 && code !== null) {
        reject(new Error(`Kimi exited with code ${code}: ${errorOutput}`));
      } else {
        resolve(output);
      }
    });
    
    kimi.on('error', (error) => {
      reject(new Error(`Failed to start kimi: ${error.message}`));
    });
    
    // 设置超时（5分钟）
    setTimeout(() => {
      kimi.kill();
      reject(new Error('Search timeout after 5 minutes'));
    }, 5 * 60 * 1000);
  });
}

/**
 * 构建搜索提示词
 */
function buildSearchPrompt(query, depth, context) {
  const depthInstructions = {
    quick: '请进行快速搜索，提供核心信息摘要（约500字）。',
    standard: '请进行标准搜索，提供详细但简洁的信息（约1000-1500字）。',
    deep: '请进行深入搜索，提供全面的信息、多个角度和细节（约2000-3000字）。'
  };
  
  let prompt = `请帮我搜索以下信息："${query}"

搜索要求：
${depthInstructions[depth] || depthInstructions.standard}

输出格式要求：
1. 使用清晰的Markdown格式
2. 包含关键信息、数据、时间线
3. 如果有多个相关主题，请分点列出
4. 注明信息来源（网站名称或类型）
5. 提供可用于进一步搜索的关键词
`;

  if (context) {
    prompt += `\n\n额外背景信息：${context}\n`;
  }
  
  prompt += `
请确保信息准确、完整，适合用于构建知识库。如果搜索结果不足，请说明并提供可能的替代搜索词。
`;

  return prompt;
}

/**
 * 保存搜索结果到文件
 */
async function saveSearchResult(query, result, category = 'general') {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const safeQuery = query.replace(/[^a-zA-Z0-9\u4e00-\u9fa5]/g, '_').substring(0, 50);
  
  // 创建目录结构
  const categoryDir = path.join(CONFIG.knowledgeBaseDir, category);
  await fs.mkdir(categoryDir, { recursive: true });
  
  // 保存搜索结果
  const resultFile = path.join(categoryDir, `${safeQuery}_${timestamp}.md`);
  const content = `# ${query}\n\n**搜索时间**: ${new Date().toLocaleString()}\n**分类**: ${category}\n\n---\n\n${result}\n\n---\n\n*Generated by kimi-search*\n`;
  
  await fs.writeFile(resultFile, content, 'utf8');
  console.log(`\n💾 搜索结果已保存: ${resultFile}`);
  
  return resultFile;
}

/**
 * 生成搜索索引
 */
async function generateSearchIndex() {
  try {
    const entries = await fs.readdir(CONFIG.knowledgeBaseDir, { withFileTypes: true });
    const categories = entries.filter(e => e.isDirectory()).map(e => e.name);
    
    let indexContent = `# Kimi 知识库索引\n\n**知识库位置**: ${CONFIG.knowledgeBaseDir}\n**最后更新**: ${new Date().toLocaleString()}\n\n## 📂 分类目录\n\n`;
    
    for (const category of categories) {
      const categoryPath = path.join(CONFIG.knowledgeBaseDir, category);
      const files = await fs.readdir(categoryPath);
      const mdFiles = files.filter(f => f.endsWith('.md') && !f.startsWith('_'));
      
      indexContent += `### ${category} (${mdFiles.length} 个文件)\n\n`;
      
      for (const file of mdFiles) {
        const filePath = path.join(categoryPath, file);
        const content = await fs.readFile(filePath, 'utf8');
        const title = content.split('\n')[0].replace('# ', '');
        const dateMatch = content.match(/\*\*搜索时间\*\*: (.+)/);
        const date = dateMatch ? dateMatch[1] : '未知';
        
        indexContent += `- [${title}](./${category}/${file}) - ${date}\n`;
      }
      
      indexContent += '\n';
    }
    
    indexContent += `\n---\n\n*使用 \`kimi-search index\` 更新此索引*\n`;
    
    const indexFile = path.join(CONFIG.knowledgeBaseDir, '_INDEX.md');
    await fs.writeFile(indexFile, indexContent, 'utf8');
    console.log(`📑 索引已更新: ${indexFile}`);
    
    return indexFile;
  } catch (error) {
    console.error('生成索引失败:', error.message);
    return null;
  }
}

/**
 * 生成快捷说明书
 */
async function generateQuickGuide() {
  const guideContent = `# Kimi Search 快捷使用指南\n\n**快速查找本地知识库中的资料**\n\n## 🚀 快速命令\n\n\`\`\`bash\n# 基础搜索\nkimi-search \"搜索内容\"\n\n# 指定分类搜索\nkimi-search \"搜索内容\" --category agents\n\n# 深度搜索\nkimi-search \"搜索内容\" --depth deep\n\n# 快速搜索\nkimi-search \"搜索内容\" --depth quick\n\n# 带背景上下文的搜索\nkimi-search \"搜索内容\" --context \"用于创建游戏角色\"\n\n# 更新索引\nkimi-search index\n\n# 显示帮助\nkimi-search --help\n\`\`\`\n\n## 📂 知识库分类\n\n| 分类 | 用途 | 示例 |\n|------|------|------|\n| \`agents\` | Agents人设信息 | 角色设定、性格特点、背景故事 |\n| \`tech\` | 技术资料 | 框架文档、API参考、教程 |\n| \`research\` | 研究报告 | 行业分析、市场调研 |\n| \`reference\` | 参考资料 | 百科、定义、概念 |\n| \`general\` | 通用搜索 | 其他杂项 |\n\n## 📝 使用场景\n\n### 场景1: 创建新Agent时查找人设\n\`\`\`bash\nkimi-search \"赛博朋克风格AI助手的性格特点和说话方式\" --category agents --context \"用于RPG游戏\"\n\`\`\`\n\n### 场景2: 寻找技术知识库\n\`\`\`bash\nkimi-search \"React Server Components 最佳实践 2024\" --category tech --depth deep\n\`\`\`\n\n### 场景3: 快速事实查证\n\`\`\`bash\nkimi-search \"Python 3.12 新特性\" --depth quick\n\`\`\`\n\n### 场景4: 研究报告\n\`\`\`bash\nkimi-search \"2024年AI行业发展趋势和市场规模\" --category research --depth deep\n\`\`\`\n\n## 🔍 搜索技巧\n\n1. **使用具体关键词** - 越具体结果越准确\n2. **添加上下文** - 使用\`--context\`说明用途\n3. **选择合适深度** - quick(快速)/standard(标准)/deep(深度)\n4. **定期整理** - 使用\`kimi-search index\`更新索引\n\n## 📁 知识库位置\n\n\`\`\`${CONFIG.knowledgeBaseDir}\`\`\`\n\n所有搜索结果按分类存储，可随时查阅。\n\n---\n\n*使用 \`kimi-search index\` 更新此指南*\n`;

  const guideFile = path.join(CONFIG.knowledgeBaseDir, '_QUICK_GUIDE.md');
  await fs.writeFile(guideFile, guideContent, 'utf8');
  console.log(`📖 快捷指南已生成: ${guideFile}`);
  
  return guideFile;
}

/**
 * 列出知识库内容
 */
async function listKnowledgeBase() {
  try {
    const entries = await fs.readdir(CONFIG.knowledgeBaseDir, { withFileTypes: true });
    const categories = entries.filter(e => e.isDirectory());
    
    console.log(`\n📚 知识库位置: ${CONFIG.knowledgeBaseDir}\n`);
    console.log(`📂 分类目录 (${categories.length} 个):\n`);
    
    let totalFiles = 0;
    for (const category of categories) {
      const categoryPath = path.join(CONFIG.knowledgeBaseDir, category.name);
      const files = await fs.readdir(categoryPath);
      const mdFiles = files.filter(f => f.endsWith('.md') && !f.startsWith('_'));
      totalFiles += mdFiles.length;
      console.log(`  📁 ${category.name}/ - ${mdFiles.length} 个文件`);
    }
    
    console.log(`\n📄 总计: ${totalFiles} 个文档\n`);
    console.log(`📖 查看索引: ${path.join(CONFIG.knowledgeBaseDir, '_INDEX.md')}`);
    console.log(`📋 快速指南: ${path.join(CONFIG.knowledgeBaseDir, '_QUICK_GUIDE.md')}`);
    
  } catch (error) {
    console.log('知识库为空，请先进行搜索。');
  }
}

/**
 * 显示帮助信息
 */
function showHelp() {
  console.log(`
🕸️ Kimi Search - 联网搜索并构建本地知识库

Usage:
  kimi-search <query> [options]       搜索信息并保存到知识库
  kimi-search index                   更新知识库索引
  kimi-search guide                   生成快捷使用指南
  kimi-search list                    列出知识库内容
  kimi-search --help                  显示帮助

Options:
  --category, -c <name>               分类目录 (默认: general)
                                      可选: agents, tech, research, reference
  --depth, -d <level>                 搜索深度 (默认: standard)
                                      quick: 快速搜索 (~500字)
                                      standard: 标准搜索 (~1000-1500字)
                                      deep: 深度搜索 (~2000-3000字)
  --context, -x <text>                添加上下文背景信息
  --output, -o <dir>                  指定输出目录

Examples:
  # 基础搜索
  kimi-search "Python 异步编程最佳实践"

  # 搜索Agents人设信息
  kimi-search "赛博朋克AI助手性格特点" --category agents

  # 深度搜索技术文档
  kimi-search "GraphQL vs REST API设计" --category tech --depth deep

  # 快速查证
  kimi-search "OpenAI最新模型" --depth quick

  # 带上下文的搜索
  kimi-search "游戏角色设计" --category agents --context "用于创建RPG游戏NPC"

环境变量:
  KIMI_SEARCH_DIR                     知识库保存路径
                                      默认: ~/Desktop/kimi-knowledge-base

Note:
  需要安装 kimi-cli 并配置好API Key
  免费版API有速率限制，请合理使用
`);
}

/**
 * 解析命令行参数
 */
function parseArgs(args) {
  const options = {
    category: 'general',
    depth: CONFIG.defaultDepth,
    context: ''
  };
  
  const queryParts = [];
  let i = 0;
  
  while (i < args.length) {
    const arg = args[i];
    
    if (arg === '--help' || arg === '-h') {
      showHelp();
      process.exit(0);
    } else if ((arg === '--category' || arg === '-c') && i + 1 < args.length) {
      options.category = args[++i];
    } else if ((arg === '--depth' || arg === '-d') && i + 1 < args.length) {
      options.depth = args[++i];
    } else if ((arg === '--context' || arg === '-x') && i + 1 < args.length) {
      options.context = args[++i];
    } else if ((arg === '--output' || arg === '-o') && i + 1 < args.length) {
      CONFIG.knowledgeBaseDir = args[++i];
    } else if (!arg.startsWith('-')) {
      queryParts.push(arg);
    }
    i++;
  }
  
  options.query = queryParts.join(' ');
  return options;
}

/**
 * 主程序
 */
async function main() {
  const args = process.argv.slice(2);
  
  // 无参数显示帮助
  if (args.length === 0) {
    showHelp();
    process.exit(0);
  }
  
  const command = args[0];
  
  try {
    // 处理子命令
    if (command === 'index') {
      await generateSearchIndex();
      process.exit(0);
    }
    
    if (command === 'guide') {
      await generateQuickGuide();
      process.exit(0);
    }
    
    if (command === 'list') {
      await listKnowledgeBase();
      process.exit(0);
    }
    
    // 搜索命令
    const options = parseArgs(args);
    
    if (!options.query) {
      console.error('❌ 错误: 请提供搜索内容');
      showHelp();
      process.exit(1);
    }
    
    // 创建知识库目录
    await fs.mkdir(CONFIG.knowledgeBaseDir, { recursive: true });
    
    // 执行搜索
    const result = await kimiSearch(options.query, options);
    
    // 保存结果
    await saveSearchResult(options.query, result, options.category);
    
    // 更新索引和指南
    await generateSearchIndex();
    await generateQuickGuide();
    
    console.log('\n✅ 搜索完成！');
    console.log(`📚 知识库位置: ${CONFIG.knowledgeBaseDir}`);
    console.log(`📑 使用 'kimi-search index' 查看索引`);
    console.log(`📖 使用 'kimi-search guide' 查看使用指南`);
    
  } catch (error) {
    console.error(`\n❌ 错误: ${error.message}`);
    process.exit(1);
  }
}

// 运行主程序
main();
